In [2]:
import numpy as np
import pandas as pd

Section 1: Python Functions

In [8]:
#Function with Parameters and Return Value
def calculate_area(length, width):
    """Calculate the area of a rectangle."""
    area = length * width
    return f"The area of the rectangle is {area} square units."

# Test the function
print(calculate_area(5, 3))



The area of the rectangle is 15 square units.


In [3]:
# Function Scope and Variable Accessibility
def outer_function():
    outer_var = 'I am outside!'
    def inner_function():
        inner_var = 'I am inside!'
        print(outer_var)  # Accessing outer scope
    inner_function()
outer_function()

I am outside!


In [9]:
# Function with default arguments
def greet_user(name, greeting="Hello"):
    """Greet the user with a custom message or a default greeting."""
    return f"{greeting}, {name}!"

# Calling with and without the optional parameter
print(greet_user("Alice"))
print(greet_user("Bob", "Welcome"))



Hello, Alice!
Welcome, Bob!


In [5]:
# Recursive function
def factorial(n):
    """Calculate factorial using recursion."""
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)
print(factorial(5))


120


In [7]:
#Fibonaci Series
def fibonacci(n):
    """Return the nth number in the Fibonacci sequence."""
    if n <= 1:
        return n
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)

# Test the recursive function
print("Fibonacci series up to 5th number:")
for i in range(6):
    print(fibonacci(i))


Fibonacci series up to 5th number:
0
1
1
2
3
5


In [6]:
#Function with Docstrings
def calculate_power(base, exponent):
    """
    Raise a number (base) to the power of another (exponent).
    Args:
        base (int, float): The base number.
        exponent (int): The power to raise the base to.
    Returns:
        int, float: Result of base raised to the power of exponent.
    """
    return base ** exponent

# Using the function with documentation
print(calculate_power(2, 3))


8


Section 2: Lambda Functions

In [12]:
#Simple Lambda Function for String Manipulation
string_to_upper = lambda s: s.upper()
# Test the function with a sample string
print(string_to_upper("hello world"))

HELLO WORLD


In [13]:
#Lamda with map function for Temp conversion
temperatures_celsius = [0, 22.5, 40, 100]
temperatures_fahrenheit = list(map(lambda c: (c * 9/5) + 32, temperatures_celsius))
print(temperatures_fahrenheit)


[32.0, 72.5, 104.0, 212.0]


In [14]:
#Lamda with filter to find even numbers
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print("Even numbers:", even_numbers)


Even numbers: [2, 4, 6, 8, 10]


In [15]:
# Lamda with reduce to calculate product
from functools import reduce
num_list = [1, 2, 3, 4, 5]
product = reduce(lambda x, y: x * y, num_list)
print("Product of all elements:", product)


Product of all elements: 120


In [16]:
#Lamda vs Regular function
def add_regular(x, y):
    return x + y

add_lambda = lambda x, y: x + y

print("Regular function result:", add_regular(5, 10))
print("Lambda function result:", add_lambda(5, 10))


Regular function result: 15
Lambda function result: 15


Section 3 Numpy

In [17]:
# Creating and Reshaping Arrays
arr = np.arange(1, 13)  # Create an array with values 1 to 12
arr_reshaped = arr.reshape(3, 4)  # Reshape into a 3x4 matrix
print("Original array:", arr)
print("Reshaped to 3x4 matrix:\n", arr_reshaped)


Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped to 3x4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
#Array Arithmetic
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Sum:", arr1 + arr2)
print("Product:", arr1 * arr2)


Sum: [5 7 9]
Product: [ 4 10 18]


In [19]:
#Indexing and Slicing
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Element at [1,1]:", arr_2d[1, 1])
print("Second row:", arr_2d[1, :])


Element at [1,1]: 5
Second row: [4 5 6]


In [20]:
#concatnation and stacking
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6], [7, 8]])
combined = np.concatenate((arr_a, arr_b), axis=0)  # Stack vertically
print("Combined array:\n", combined)


Combined array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [21]:
#random number generation
random_array = np.random.randint(1, 100, size=(4, 3))
print("4x3 array of random integers:\n", random_array)


4x3 array of random integers:
 [[93 94 72]
 [34 41 19]
 [58 69 76]
 [60 64 29]]


Section 4 Pandas

In [26]:
#Createing DataFrames and adding column
data = {'Name': ['Alice', 'Bob', 'Charles'], 'Age': [24, 27, 22]}
df = pd.DataFrame(data)
df['Score'] = [88, 92, 85]  # Add new column
print(df)


      Name  Age  Score
0    Alice   24     88
1      Bob   27     92
2  Charles   22     85


In [25]:
df = pd.read_csv('/accounts.csv')
print("Data loaded from CSV:\n", df.head())


Data loaded from CSV:
    account_id  customer_id account_type  balance
0           1           45      Savings  1000.50
1           2           12     Checking  2500.75
2           3           78      Savings  1500.00
3           4           34     Checking  3000.25
4           5           56      Savings   500.00


In [27]:
df['Score'].fillna(df['Score'].mean(), inplace=True)  # Replace NaN with mean


<ipython-input-27-89e95a8c115c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Score'].fillna(df['Score'].mean(), inplace=True)  # Replace NaN with mean


If Statements

In [29]:
# Complex If-Else Statement
score = 85
if score >= 90:
    grade = 'A'
elif score >= 80:
    grade = 'B'
elif score >= 70:
    grade = 'C'
else:
    grade = 'D'
print("Grade:", grade)


Grade: B


In [33]:
#Using Multiple Conditions with and and or Operators
age = 30
income = 40000

if age > 25 and income >= 30000:
    print("Eligible for loan.")
elif age <= 25 and income >= 30000:
    print("Income qualifies, but age is too low.")
elif age > 25 and income < 30000:
    print("Age qualifies, but income is too low.")
else:
    print("Does not qualify for loan.")


Eligible for loan.


In [34]:
#Nested If Statements for Complex Decision-Making
score = 78

if score >= 90:
    grade = 'A'
    if score > 95:
        comment = "Excellent!"
    else:
        comment = "Great job!"
elif score >= 80:
    grade = 'B'
    comment = "Good work."
elif score >= 70:
    grade = 'C'
    if score >= 75:
        comment = "Keep it up!"
    else:
        comment = "Needs improvement."
else:
    grade = 'D'
    comment = "Consider extra help."

print(f"Grade: {grade} - {comment}")


Grade: C - Keep it up!


In [35]:
#Using Conditional Statements with Lists
fruits = ["apple", "banana", "orange"]
fruit_to_check = "banana"

if fruit_to_check in fruits:
    print(f"{fruit_to_check.capitalize()} is available!")
else:
    print(f"{fruit_to_check.capitalize()} is not in the list.")


Banana is available!


In [36]:
#Checking Multiple Conditions with elif
temperature = 32  # in degrees Celsius

if temperature > 35:
    print("It's very hot outside.")
elif 25 <= temperature <= 35:
    print("The weather is warm.")
elif 15 <= temperature < 25:
    print("It's mild outside.")
elif 5 <= temperature < 15:
    print("It's getting chilly.")
else:
    print("It's cold outside.")


The weather is warm.


In [37]:
#Complex Condition with Nested if and Logical Operators
gpa = 3.6
extracurriculars = ["volunteer work", "sports"]
has_leadership_role = True

if gpa >= 3.5:
    if "volunteer work" in extracurriculars and has_leadership_role:
        print("Eligible for a full scholarship.")
    elif "volunteer work" in extracurriculars or has_leadership_role:
        print("Eligible for a partial scholarship.")
    else:
        print("Eligible for academic scholarship only.")
else:
    print("Not eligible for a scholarship.")


Eligible for a full scholarship.


loops

In [38]:
#For Loop with List of Dictionaries
employees = [
    {"name": "Alice", "role": "Developer", "salary": 70000},
    {"name": "Bob", "role": "Designer", "salary": 65000},
    {"name": "Charlie", "role": "Manager", "salary": 90000}
]

for employee in employees:
    print(f"{employee['name']} works as a {employee['role']} with a salary of {employee['salary']}")


Alice works as a Developer with a salary of 70000
Bob works as a Designer with a salary of 65000
Charlie works as a Manager with a salary of 90000


In [39]:
# While Loop with Counter
counter = 5
while counter > 0:
    print(f"Counting down: {counter}")
    counter -= 1
print("Countdown finished!")


Counting down: 5
Counting down: 4
Counting down: 3
Counting down: 2
Counting down: 1
Countdown finished!


In [43]:
#Nested For Loops to Generate Multiplication Table
for i in range(1, 21):
    for j in range(1, 15):
        print(f"{i} x {j} = {i * j}", end="\t")
    print()  # New line after each row


1 x 1 = 1	1 x 2 = 2	1 x 3 = 3	1 x 4 = 4	1 x 5 = 5	1 x 6 = 6	1 x 7 = 7	1 x 8 = 8	1 x 9 = 9	1 x 10 = 10	1 x 11 = 11	1 x 12 = 12	1 x 13 = 13	1 x 14 = 14	
2 x 1 = 2	2 x 2 = 4	2 x 3 = 6	2 x 4 = 8	2 x 5 = 10	2 x 6 = 12	2 x 7 = 14	2 x 8 = 16	2 x 9 = 18	2 x 10 = 20	2 x 11 = 22	2 x 12 = 24	2 x 13 = 26	2 x 14 = 28	
3 x 1 = 3	3 x 2 = 6	3 x 3 = 9	3 x 4 = 12	3 x 5 = 15	3 x 6 = 18	3 x 7 = 21	3 x 8 = 24	3 x 9 = 27	3 x 10 = 30	3 x 11 = 33	3 x 12 = 36	3 x 13 = 39	3 x 14 = 42	
4 x 1 = 4	4 x 2 = 8	4 x 3 = 12	4 x 4 = 16	4 x 5 = 20	4 x 6 = 24	4 x 7 = 28	4 x 8 = 32	4 x 9 = 36	4 x 10 = 40	4 x 11 = 44	4 x 12 = 48	4 x 13 = 52	4 x 14 = 56	
5 x 1 = 5	5 x 2 = 10	5 x 3 = 15	5 x 4 = 20	5 x 5 = 25	5 x 6 = 30	5 x 7 = 35	5 x 8 = 40	5 x 9 = 45	5 x 10 = 50	5 x 11 = 55	5 x 12 = 60	5 x 13 = 65	5 x 14 = 70	
6 x 1 = 6	6 x 2 = 12	6 x 3 = 18	6 x 4 = 24	6 x 5 = 30	6 x 6 = 36	6 x 7 = 42	6 x 8 = 48	6 x 9 = 54	6 x 10 = 60	6 x 11 = 66	6 x 12 = 72	6 x 13 = 78	6 x 14 = 84	
7 x 1 = 7	7 x 2 = 14	7 x 3 = 21	7 x 4 = 28	7 x 5 = 35	7 x 6 

In [44]:
#For Loop with break and continue
numbers = [1, 2, 3, 4, 5, 6]
for num in numbers:
    if num == 3:
        continue  # Skip number 3
    elif num == 5:
        break  # Stop the loop when reaching number 5
    print(num)


1
2
4


In [45]:
#Using While Loop to Sum Input Numbers
total = 0
while True:
    num = input("Enter a number to add (or 'stop' to end): ")
    if num.lower() == 'stop':
        break
    total += int(num)
print("Total sum:", total)


Enter a number to add (or 'stop' to end): 5
Enter a number to add (or 'stop' to end): 2
Enter a number to add (or 'stop' to end): 6
Enter a number to add (or 'stop' to end): stop
Total sum: 13


Section 7: Lists, Tuples, Sets, and Dictionaries

In [46]:
#Working with Lists: Adding, Removing, and Slicing
fruits = ["apple", "banana", "cherry"]
fruits.append("date")  # Add an item
fruits.remove("banana")  # Remove an item
print("Sliced fruits:", fruits[1:])  # Slicing


Sliced fruits: ['cherry', 'date']


In [47]:
# Using Tuples to Store Fixed Data
location = ("New York", "USA")
city, country = location  # Tuple unpacking
print(f"City: {city}, Country: {country}")


City: New York, Country: USA


In [48]:
# Working with Sets: Adding, Removing, and Checking Membership
languages = {"Python", "Java", "C++"}
languages.add("JavaScript")  # Add a new item
languages.discard("Java")  # Remove an item
print("Contains Python:", "Python" in languages)


Contains Python: True


In [49]:
#Dictionary Operations: Adding, Updating, and Looping Through Items
student = {"name": "Alice", "age": 23, "major": "Computer Science"}
student["grade"] = "A"  # Add a new key-value pair
student["age"] = 24  # Update an existing key-value pair

for key, value in student.items():
    print(f"{key}: {value}")


name: Alice
age: 24
major: Computer Science
grade: A


In [50]:
#Using Sets to Find Unique Values
numbers = [1, 2, 2, 3, 4, 4, 5]
unique_numbers = set(numbers)
print("Unique numbers:", unique_numbers)


Unique numbers: {1, 2, 3, 4, 5}


Section 8: Operators

In [51]:
#Arithmetic Operators
a, b = 10, 3
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Modulus:", a % b)
print("Exponentiation:", a ** b)


Addition: 13
Subtraction: 7
Multiplication: 30
Division: 3.3333333333333335
Modulus: 1
Exponentiation: 1000


In [52]:
# Comparison Operators
a, b = 5, 10
print("a equals b:", a == b)
print("a not equal to b:", a != b)
print("a greater than b:", a > b)
print("a less than or equal to b:", a <= b)


a equals b: False
a not equal to b: True
a greater than b: False
a less than or equal to b: True


In [53]:
#Logical Operators
is_active = True
is_member = False
print("Can access:", is_active and is_member)
print("Either active or member:", is_active or is_member)
print("Not active:", not is_active)


Can access: False
Either active or member: True
Not active: False


In [54]:
#Assignment Operators
x = 5
x += 2  # Equivalent to x = x + 2
x *= 3  # Equivalent to x = x * 3
print("Value of x:", x)


Value of x: 21


In [55]:
#Operator Precedence Example
result = 5 + 3 * 2 ** 2  # Exponentiation first, then multiplication, then addition
print("Result with precedence:", result)


Result with precedence: 17


Reading CSV Files with Pandas

In [3]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
print(df.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0  


In [4]:
#Reading CSV with Custom Delimiter
df = pd.read_csv('/content/sample_data/california_housing_test.csv', delimiter=';')
print(df.head())

  longitude,"latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income","median_house_value"
0  -122.050000,37.370000,27.000000,3885.000000,66...                                                                                     
1  -118.300000,34.260000,43.000000,1510.000000,31...                                                                                     
2  -117.810000,33.780000,27.000000,3589.000000,50...                                                                                     
3  -118.360000,33.820000,28.000000,67.000000,15.0...                                                                                     
4  -119.670000,36.330000,19.000000,1241.000000,24...                                                                                     


In [5]:
#Handling Missing Values
df = pd.read_csv('/content/sample_data/california_housing_test.csv', na_values=['NA', 'N/A', ''])
print("Data with missing values handled:\n", df.head())

Data with missing values handled:
    longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0  


Section 10: Python String Methods

In [56]:
#Uppercase and Lowercase Conversion
text = "Hello, World!"
print("Uppercase:", text.upper())
print("Lowercase:", text.lower())


Uppercase: HELLO, WORLD!
Lowercase: hello, world!


In [57]:
#Replacing Parts of a String
text = "I love programming in Python!"
modified_text = text.replace("Python", "JavaScript")
print("Modified text:", modified_text)


Modified text: I love programming in JavaScript!


In [58]:
#Checking if String Starts/Ends with a Substring
text = "data_science_project.csv"
print("Starts with 'data':", text.startswith("data"))
print("Ends with '.csv':", text.endswith(".csv"))


Starts with 'data': True
Ends with '.csv': True


In [59]:
#Splitting and Joining Strings
sentence = "Python is a versatile language"
words = sentence.split()  # Split by whitespace
joined_sentence = "-".join(words)
print("Words:", words)
print("Joined sentence:", joined_sentence)


Words: ['Python', 'is', 'a', 'versatile', 'language']
Joined sentence: Python-is-a-versatile-language


In [60]:
#Removing Whitespace
messy_string = "   Hello, World!   "
print("Original string:", repr(messy_string))
print("Without leading and trailing whitespace:", repr(messy_string.strip()))


Original string: '   Hello, World!   '
Without leading and trailing whitespace: 'Hello, World!'
